### ISSUE TITLE
Language ID `cmn` is deprecated

### ISSUE THREAD

**Issue by geekpany** [mike-fabian/langtable#8]
> Macrolanguage subtag "zh" (Chinese) is used instead of "cmn" (Mandarin)

source:  http://cldr.unicode.org/index/cldr-spec/picking-the-right-language-code#TOC-Caution-

So, I think the following part should be removed from `data/languages.xml`

```
  <language>
    <languageId>cmn</languageId>
    ...
  </language>
```

**Comment by mike-fabian** [comment]
I think cmn can stay  in langtable because anaconda  should only show  the languages where translations  exist in Zanata, as  you reported here:
https://bugzilla.redhat.com/show_bug.cgi?id=1678787

A cmn_TW  locale  exists in glibc by the way.

langtable tries to be  as  complete as possible, it also  has  entries for some  legacy language  codes  like "iw" and  "no".

**Comment by mike-fabian** [comment]
The author of cmn_TW disagrees, he thinks zh_TW should be deprecated,
see:

https://sourceware.org/bugzilla/show_bug.cgi?id=17563#c7

**Comment by geekpany** [comment]
Please check this issue opened by the author of cmn_TW:
https://bugzilla.redhat.com/show_bug.cgi?id=1707640

> nan, hak, yue, and cmn are all spoken languages, not the written system.

**Comment by mike-fabian** [comment]
In https://github.com/mike-fabian/langtable/releases/tag/0.0.43

I reduced the rank of cmn_TW.UTF-8 and zh_SG.UTF-8 to 0 for languageId="zh".

That means, cmn_TW.UTF-8 and zh_SG.UTF-8 should not appear in the language selection page  of anaconda anymore. This should reduce the confusion as we  don’t have translations  for these  locales anyway.
