### ISSUE TITLE
Default keyboard layout for Afrikaans (af)

### ISSUE THREAD

**Issue by friedelwolff** [mike-fabian/langtable#9]
The current default keyboard layout for the Afrikaans language is the US layout which doesn't provide any of the diacritics that are in use in the language. The US layout is the common layout for hardware sold in South Africa, but Afrikaans can't be typed properly with it. I've noticed this incorrect default on Fedora before, but it is not my main system. It has always been some variant of US-intl on Mageia and its predecessors, which is a very good default (behaving mostly the same as the US layout anyway).

It seems that "us(altgr-intl)" would be a better default for Afrikaans, although I can't see precisely what that corresponds to on my system. On my system there is "English (US, alt. intl.)" and "English (US, intl, with dead keys)". They are pretty similar and either would be a better default than the plain US layout.

Feel free to ask if anything else is required.

**Comment by mike-fabian** [comment]
So which one would be the best default? I think these are available:
```
mfabian@taka:/usr/share/X11/xkb/symbols
$ grep xkb_symbols.*intl us 
xkb_symbols "intl" {
xkb_symbols "alt-intl" {
xkb_symbols "dvorak-intl" {
xkb_symbols "dvorak-alt-intl" {
xkb_symbols "altgr-intl" {
xkb_symbols "classmate-intl" {
xkb_symbols "classmate-alt-intl" {
xkb_symbols "classmate-altgr-intl" {
xkb_symbols "workman-intl" {
xkb_symbols "carpalx-intl" {
xkb_symbols "carpalx-altgr-intl" {
xkb_symbols "carpalx-full-intl" {
xkb_symbols "carpalx-full-altgr-intl" {
xkb_symbols "intl-unicode" {
xkb_symbols "alt-intl-unicode" {
mfabian@taka:/usr/share/X11/xkb/symbols
$ 

```

**Comment by friedelwolff** [comment]
Ok, in that file I was able to reconcile the name in the GUI with the xkb name. Thank you.

I think "intl" is the best. A second best would be "alt-intl" which can type everything required by the language and is simpler (but lacks a few niceties). I don't know if simplicity is a goal. If it is, "alt-intl" might be better since it has fewer surprises.

**Comment by mike-fabian** [comment]
> I don't know if simplicity is a goal.

I don’t know either, the default should be what most users of Afrikaans prefer, whatever that is.

**Comment by mike-fabian** [comment]
So maybe it would be OK like this?:

https://github.com/mike-fabian/langtable/commit/e9169a414d9cf0d4c34f5b88c770aa0a250a58f9

**Comment by friedelwolff** [comment]
No, I think there are a few issues with that commit. I'll try to provide comments a bit later.

**Comment by mike-fabian** [comment]
What issues  do you see with that  commit?

**Comment by friedelwolff** [comment]
Sorry, I was pressed for time and my wording was maybe not ideal. You obviously know the codebase much better, and I had to familiarise myself with the `_test_language_territory()` function. Only two things to discuss:

 - langtable/data/keyboards.xml: <territoryId>AF</territoryId> - Doesn't this refer to Afghanistan? The country code for South Africa is ZA.
- Other data is needed for the other South African languages. I added that separately in issue #10. 

Thank you for the help!

**Comment by mike-fabian** [comment]
> langtable/data/keyboards.xml: AF - Doesn't this refer to Afghanistan? The country code for South Africa is ZA

Good catch! That was a typo, of course I wanted to write ZA there.

**Comment by friedelwolff** [comment]
Sorry if my  feedback is coming in small chunks, but another matter: I wouldn't recommend us(intl) for other languages, only for Afrikaans (af). The dead keys would surprise too many people who won't benefit form it, and it isn't suitable for the languages mentioned in issue #10 (nso, ve or tn).

**Comment by mike-fabian** [comment]
Do you think what I currently have in this branch is OK?:

https://github.com/mike-fabian/langtable/commits/release-0.0.45

I made the "za" keyboard layout the default for nso, ve, and tn.

**Comment by mike-fabian** [comment]
For the other languages spoken in ZA, zu xh st ts ss nr, is us(intl) OK or
should these use the za keyboard layout by default?

**Comment by friedelwolff** [comment]
They are ASCII only (for all practical purposes), so I think plain "us" is best with fewest surprises. The only advantage of "za" for these languages is that the users would be able to type names of people and places with diacritics, but that is really not that common.

**Comment by mike-fabian** [comment]
OK, currently the plain “us” layout is used for these languages already

```
$ python3 
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import langtable
>>> langtable.list_keyboards(languageId='zu')
['us']
>>> langtable.list_keyboards(languageId='xh')
['us']
>>> langtable.list_keyboards(languageId='st')
['us']
>>> langtable.list_keyboards(languageId='ts')
['us']
>>> langtable.list_keyboards(languageId='ss')
['us']
>>> langtable.list_keyboards(languageId='nr')
['us']
>>> 
```

So I don’t need to change anything there.

That means my current two patches are OK, I guess.

**Comment by mike-fabian** [comment]
Is it OK?

**Comment by friedelwolff** [comment]
It looks right. I wanted to check if specifying territoryId still gives the desired results, but since it doesn't install correctly from git with a simple pip install, I couldn't check quickly. Thank you for your responses!

**Comment by mike-fabian** [comment]
Is pip install from git possible?

**Comment by mike-fabian** [comment]
You don’t need to install to test. If you have a git clone,
you can use it from the top level directory of the source.
Like this:

```
mfabian@taka:/local/mfabian/src/langtable (release-0.0.45)
$ python3
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import langtable
>>> langtable.info()
Version: = 0.0.44
Loaded from: /local/mfabian/src/langtable/langtable/langtable.py
Data files read: ['/local/mfabian/src/langtable/langtable/data/territories.xml', '/local/mfabian/src/langtable/langtable/data/languages.xml', '/local/mfabian/src/langtable/langtable/data/keyboards.xml', '/local/mfabian/src/langtable/langtable/data/timezones.xml', '/local/mfabian/src/langtable/langtable/data/timezoneidparts.xml']
>>> langtable.list_keyboards(territoryId="ZA")
['us(intl)', 'za']
>>>
```

langtable.info() shows you that the source and data files were loaded directly from the git clone and not from something installed elsewhere on the system.

**Comment by friedelwolff** [comment]
Sorry that this is turning into a support issue. It isn't working directly from a clone for me:

```
>>> import langtable
>>> langtable.info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...../download/langtable/langtable/langtable.py", line 1940, in info
    version = pkg_resources.require("langtable")[0].version
  File "...../download/langtable/env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/wolfff/download/langtable/env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'langtable' distribution was not found and is required by the application
```
The function calls seem to work, though, so I'll comment briefly on that.

Your output with territoryId="ZA" is what I'm concerned about: I think the "us" layout should still be suggested for South Africa as the default for English and the other ASCII languages, but is not shown in that list. Maybe in a future release we can recommend "za" for all of them, but I'd prefer to make small changes to disrupt less people's workflows... not that I'm expecting a lot of feedback.

It seems that .list_keyboards() combines results for language and territory, is that correct?
```python
>>> langtable.list_keyboards(languageId="zu", territoryId="ZA")
['us', 'us(intl)', 'za']
```

For this I was expecting only "us", but I guess I misunderstood what the function is for.

**Comment by mike-fabian** [comment]
I forgot that langtable.info() works only after one did a “make dist” in the toplevel directory of the git clone. Because “make dist” creates langtable.egg-info/PKG-INFO which is where langtable.info() tries to get the version from:
```
$ grep -i version langtable.egg-info/PKG-INFO
Metadata-Version: 1.1
Version: 0.0.45
```

**Comment by mike-fabian** [comment]
.list_keyboards() returns a list of layouts which could possibly be used for the language and/or territory (This may include some unlikely ones although *extremely* unlikely ones are dropped from that list by default). The really interesting value is only the first value of that list because that is going to be the default for that language and/or territory.

I have added "us" to "ZA" now because you are right, it is a possible layout for "ZA". 

> It seems that .list_keyboards() combines results for language and territory, is that correct?

Yes, but it may reorder them and drop very unlikely stuff from that list.

The only really interesting thing is whether the first item of the resulting list is what we want as the default for that combination of language and/or territory.

**Comment by friedelwolff** [comment]
Ok, I almost managed to make things, but my gzip version is to old (doesn't support --keep). I simulated the "make dist" step, and the warnings are gone. With your latest comments on what is important for .list_keyboards():
 - I think "us" and maybe even "za" should be offered for language "af" as secondary choices.
 - .list_keyboards(languageId="en", territoryId="ZA") gives 'us(intl)' in first position, which should be "us". I'm not sure what the best order is after that.

But we're approaching the territory of splitting hairs now. I hope my comments have been useful!

**Comment by mike-fabian** [comment]
I added “us” back to the possible layouts for “ZA”. It makes no significant difference in the results for .list_keyboards() the first value of the lists returned doesn’t change, but it shows that “us” is a “possible” layout for “ZA”.

After updating the release candidate branch release-0.0.45 I now have this:

```
$ python3
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import langtable
>>> langtable.list_keyboards(territoryId='ZA')
['us(intl)', 'us', 'za']
```

That means that all three layouts are somehow “possible” if you only know “ZA”, because some language spoken in “ZA” uses that layout. But, if you only know “ZA” and nothing else, the default layout should be “us(intl)”, that is the best compromise if you know only “ZA” but not the language. Actually I think this case isn’t even important because as far as I know Anaconda always chooses a layout based on language *and* territory. If Anaconda gets the territory automatically from your location for example using your ip-address, it will get the most likely locales for that territory from langtable. So if anaconda guesses you are in “ZA”, then 

```
>>> langtable.list_locales(territoryId='ZA')
['zu_ZA.UTF-8', 'xh_ZA.UTF-8', 'af_ZA.UTF-8', 'en_ZA.UTF-8', 'nso_ZA.UTF-8', 'tn_ZA.UTF-8', 'st_ZA.UTF-8', 'ts_ZA.UTF-8', 'ss_ZA.UTF-8', 've_ZA.UTF-8', 'nr_ZA.UTF-8']
>>>
```

and take the first value from that list as the “most likely” choice. And then get the default keyboard layout for that choice by doing

```
>>> langtable.list_keyboards(languageId='zu_ZA')
['us']
>>> langtable.list_keyboards(languageId='zu', territoryId='ZA')
['us']

```

(It does not matter whether one specifies languageId='xx', territoryId='YY' or langaugeId='xx_YY', the result should be always the same).

In the first page of anaconda, the user can also manually choose the language and the locale.
If one chooses a language at the left side, a list of locales for that language is offered at the right side.
For example:

```
>>> langtable.list_locales(languageId='de')
['de_DE.UTF-8', 'de_AT.UTF-8', 'de_CH.UTF-8', 'de_IT.UTF-8', 'de_LI.UTF-8', 'de_BE.UTF-8', 'de_LU.UTF-8']
>>> 
```

So if the language choose is “de”, (German), then there are glibc locales available for German in Germany, German in Austria, German in Switzerland, ...
and the user can choose one.

In any case, when anaconda proceeds the next page, it has a full glibc locale name like xx_YY.UTF-8,
whether that has been chosen automatically or whether the user has selected it manually.

Then the only thing which really matters is whether the default keyboard layout for the full locale name, i.e. the combination of language and territory comes out correctly. The default is the first value of the list returned, the other values of the list can really be ignored and don’t matter, they are interesting only when you are tweaking the numbers in langtable to see how the lists change. The numbers don’t really mean anything, they just have to be adjusted so that the first value of the returned list is always what should be the default.

```
>>> langtable.list_keyboards(languageId='zu')
['us']
```

So if one only knows 'zu', the default layout should be “us”

```
>>> langtable.list_keyboards(languageId='zu_ZA')
['us']
```

If one also knows the territory, “ZA”, the default keyboard layout for “zu” remains “us”.

For some languages, there are different default layouts depending on the territory, for example if you only
know “de”

```
>>> langtable.list_keyboards(languageId='de')
['de(nodeadkeys)', 'de(deadacute)', 'at(nodeadkeys)', 'ch', 'be(oss)']
```

the default layout is “de(nodeadkeys)” because that is the default in Germany where the most speakers of German are.

Specifying the territory “DE” as well does not change the result, the first value is unchanged:

```
>>> langtable.list_keyboards(languageId='de_DE')
['de(nodeadkeys)', 'de(deadacute)']
```

Some other values from the list for only “de” have been dropped because in the calculation of combining the results they got extremely tiny scores. But what really matters is that the first value “de(nodeadkeys)” is correct.

If one uses Switzerland, “CH”, as the territory, one gets:

```
>>> langtable.list_keyboards(languageId='de_CH')
['ch']
>>> 
```

I.e. the Swiss keyboard layout, whis is the right default for German in Switzerland.

The important thing is only that the first value .list_keyboards() always comes out right, the numbers in the xml files of langtable can be freely tweaked as needed to achieve that result.

For South Africa we now have:

```
>>> langtable.list_keyboards(languageId='zu_ZA')
['us']
>>> langtable.list_keyboards(languageId='xh_ZA')
['us']
>>> langtable.list_keyboards(languageId='af_ZA')
['us(intl)']
>>> langtable.list_keyboards(languageId='en_ZA')
['us']
>>> langtable.list_keyboards(languageId='nso_ZA')
['za']
>>> langtable.list_keyboards(languageId='tn_ZA')
['za']
>>> langtable.list_keyboards(languageId='st_ZA')
['us']
>>> langtable.list_keyboards(languageId='ts_ZA')
['us']
>>> langtable.list_keyboards(languageId='ss_ZA')
['us']
>>> langtable.list_keyboards(languageId='ve_ZA')
['za']
>>> langtable.list_keyboards(languageId='nr_ZA')
['us']
>>>
```

As long as the first value of the lists returned is correct, the rest doesn’t matter much.

For debugging purposes when tweaking the numbers to get the right defaults, one can use concise=False to prevent dropping extremely unlikely results from the lists and show_weights=True to see which numbers came out when doing the calculations. Like this:

```
>>> langtable.list_keyboards(concise=False, show_weights=True, languageId='nso', territoryId='ZA')
[['za', 100000000000], ['us(intl)', 700], ['us', 200]]
>>> 
```

But that is only for debugging when you tweak the numbers to get the right defaults.

**Comment by friedelwolff** [comment]
Thank you for the thorough comment. I've now translated Anaconda, so with this change the whole experience will be very good with the next release of Fedora.

**Comment by mike-fabian** [comment]
https://github.com/mike-fabian/langtable/releases/tag/0.0.45

contains the changes for the default keyboard layouts for the  *_ZA locales.
